USE sac;

-- tabla equipo

INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('1','NETWORK ANALYZER HP AGILENT  8753C 300 KHZ -3GHZ','Indefinido','Indefinido','10001','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('2','REAL TIME SPECTRUM ANALYZER RSA3303B DC-3GHZ TEKTRONIX','Proyecto de sistemas embebidos','2009','10002','7','3');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('3','ANALOG SIGNAL GENERATOR N5181A MXG RF AGILENT - UP TO 6 GHZ','Proyecto de sistemas embebidos','2008','10003','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('4','WAVETESTER  SISTEMA PARA ADQUISICION DE DATOS. MEET','Harina de Pescado con tierracolorada (Proyecto de PTC)','2010','10004','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('5','WAVETESTER  SISTEMA PARA ADQUISICION DE DATOS. MEET','Proyecto de maestría','Indefiniido','10004','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('6','WAVETESTER  SISTEMA PARA ADQUISICION DE DATOS. MEET','Proyecto de maestría','Indefinido','10004','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('7','DIGITAL STORAGE OSCILLOSCOPE INSTEK GDS-820 - 150 MHZ ','Proyecto de provesamiento de imágenes','Indefinido','10005','7','2');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('8','EXPERIMENTAL 3D PRINTER MAKERBOT REPLICATOR 2X','Procesamiento de imágenes','2015','10006','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('9','MODULO DE PH FESTO','Proyecto de posgrado','Indefinido','10007','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('10','MODULO DE CONTROL DE MOTORES FESTO','Proyecto de posgrado','indefinido','10008','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('11','MODULO COMPACT WORKSTATION FESTO','Modelo matemático de evaporadores multietapa','2009','10009','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('12','QUAD COPTER','Armado en el lab','Indefinido','10010','7','5');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('13','QUAD COPTER','Armado en el lab','Indefinido','10010','7','5');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('14','MÓDULO DSPACE DS1104 R&D CONTROLLER BOARD','Proyecto de evaporadores','2010','10011','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('15','COMPACT FIELD POINT NATIONAL','Proyecto de sistemas embebidos','2008','10012','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('16','OPTO 22','Indefinido','Indefinido','10004','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('17','PLC VIPA ® CPU 314SC , ','Indefinido','Indefinido','10013','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('18','PLC  SIEMENS S7 - 300','Indefinido','Indefinido','10013','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('19','DIRECT LOGIC 05 PROGRAMMABLE LOGIC CONTROLLER PLC','Proyecto de sistemas embebidos','2008','10013','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('20','DIRECT LOGIC 05 PROGRAMMABLE LOGIC CONTROLLER PLC','Proyecto de sistemas embebidos','2008','10013','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('21','DIRECT LOGIC 05 PROGRAMMABLE LOGIC CONTROLLER PLC','Proyecto de sistemas embebidos','2008','10013','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('22','DIRECT LOGIC 05 PROGRAMMABLE LOGIC CONTROLLER PLC','Proyecto de sistemas embebidos','2008','10013','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('23','DIRECT LOGIC 06 PROGRAMMABLE LOGIC CONTROLLER PLC','Proyecto de sistemas embebidos','2008','10013','9','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('24','MOTOR TRIFÁSICO SIEBER SARL','Indefinido','Indefinido','10014','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('25','VARIADOR DE VELOCIDAD AUTOMATION','Indefinido','Indefinido','10015','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('26','PH-METRO NATIONAL','Proyecto de biodigestor','2015','10016','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('27','BOMBA DOSIFICADORA ELECTRÓNICA NSF','Proyecto de sistemas embebidos','2008','10017','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('28','BOMBA DOSIFICADORA ELECTRÓNICA NSF','Proyecto de sistemas embebidos','2008','10017','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('29','LEGO MINDSTORN','Proyecto de fermentación','2015','10018','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('30','LEGO MINDSTORN','Proyecto de fermentación','2015','10018','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('32','MÁQUINA DE METALIZADO','Proyecto de fermentación','2015','10019','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('33','ESTACIÓN DE SOLDAR','Proyecto de fermentación','2015','10020','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('34','COMPRESOR DE AIRE  HYAC 50 D','Indefinido','Indefinido','10021','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('35','AGITADOR MAGNÉTICO VELP','Proyecto de sistemas embebidos','Indefinido','10022','9','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('36','SERVIDOR HP PROLIANT ML350P GEN8','Indefinido','Indefinido','10023','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('37','SERVIDOR DE ALMACENAMIENTO EN RED NAS 8TB  LENOVO STORAGE IX4 300D','Proyecto de equipamiento','2019','10023','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('38','SERVIDOR SUPERSERVER 8048B-COR4FT','Proyecto de equipamiento','2019','10023','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('39','QUICK CIRCUIT 3000 T-TECH QUICK CIRCUIT PROTOTYPING SYSTEMS','Proyecto de fermentación','2015','10024','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('40','TARJETA PSOC FAMILIA KIT 001 CYPRESS','Proyecto de sistemas embebidos','2010','10025','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('41','TARJETA PSOC FAMILIA KIT 001 CYPRESS','Proyecto de sistemas embebidos','2010','10025','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('42','EVALUATION SYSTEM WITH ZIGBEE CYPRESS','Proyecto de sistemas embebidos','2010','10026','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('43','EVALUATION SYSTEM WITH ZIGBEE CYPRESS','Proyecto de sistemas embebidos','2010','10026','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('44','TARJETA PSOC EVALUATION KIT CYPRESS','Proyecto de sistemas embebidos','2010','10025','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('45','TARJETA PSOC EVALUATION KIT CYPRESS','Proyecto de sistemas embebidos','2010','10025','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('46','TARJETAS PSOC FAMILIA 4 CYPRESS','Proyecto de sistemas embebidos','2010','10027','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('47','TARJETAS PSOC FAMILIA 4 CYPRESS','Proyecto de sistemas embebidos','2010','10027','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('48','TARJETAS FPGA VIRTEX 5 XILINX','Proyecto de sistemas embebidos','2010','10027','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('49','TARJETA FPGA SPARTAN XILINX','Proyecto de sistemas embebidos','2010','10027','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('50','TARJETA BEAGLEBONE','Proyecto de procesamiento de imágenes','2015','10027','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('51','TARJETAS RASPBERRY PI ','Proyecto de procesamiento de imágenes','2015','10027','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('52','TARJETAS RASPBERRY PI ','Proyecto de procesamiento de imágenes','2015','10027','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('53','TARJETAS RASPBERRY PI ','Proyecto de procesamiento de imágenes','2015','10027','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('54','TARJETAS RASPBERRY PI ','Proyecto de procesamiento de imágenes','2015','10027','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('55','TARJETAS PHIDGETS','Proyecto de sistemas embebidos','2010','10027','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('56','TARJETAS PHIDGETS','Proyecto de sistemas embebidos','2010','10027','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('57','TARJETAS PHIDGETS','Proyecto de sistemas embebidos','2010','10027','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('58','TARJETAS PHIDGETS','Proyecto de sistemas embebidos','2010','10027','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('59','TARJETAS PHIDGETS','Proyecto de sistemas embebidos','2010','10027','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('60','DESKTOP COMPATIBLE','Indefinido','Indefinido','10028','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('61','DESKTOP COMPATIBLE','Indefinido','Indefinido','10028','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('62','DESKTOP COMPATIBLE','Indefinido','Indefinido','10028','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('63','DESKTOP COMPATIBLE','Indefinido','Indefinido','10028','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('64','DESKTOP COMPATIBLE','Indefinido','Indefinido','10028','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('65','DESKTOP COMPATIBLE','Indefinido','Indefinido','10028','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('66','LAPTOPS VARIAS','Indefinido','Indefinido','10029','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('67','LAPTOPS VARIAS','Indefinido','Indefinido','10029','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('68','LAPTOPS VARIAS','Indefinido','Indefinido','10029','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('69','LAPTOPS VARIAS','Indefinido','Indefinido','10029','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('70','LAPTOPS VARIAS','Indefinido','Indefinido','10029','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('71','LAPTOPS VARIAS','Indefinido','Indefinido','10029','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('72','LAPTOPS VARIAS','Indefinido','Indefinido','10029','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('73','CAMARA HIPERESPECTRAL RESONON, PIKA 2G, 400-900NM','Proyecto de procesamiento de imágenes','2015','10030','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('74','CAMARA HIPERESPECTRAL SPECIMEN, SWIR, 1000-2500NM','Proyecto equipamiento','2019','10030','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('75','CAMARA MULTIESPECTRAL MICASENSE','Proyecto de equipamiento','2019','10031','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('76','DRONE MATRICE M210','Poryecto de equipamiento','2019','10032','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('77','DRONE MATRICE M610','Proyecto doctorado','2019','10032','7','1');
INSERT INTO equipo(IdEquipo,Descripción,Procedencia,Año_Adquisicion,IdTipo,IdUbi,IdEstado)VALUES('78','SISTEMAS DE MEDICION RED DE MONITOREO MICROLINK','Proyecto de agrosavia','2021','10033','7','1');


-- si se van a agregar registros directamente a la DB hacerlo después de este comentario

