USE sac;

-- tabla autor

INSERT INTO autor(IdAutor,Autor)VALUES('100001','R. Vichnevetzky');
INSERT INTO autor(IdAutor,Autor)VALUES('100002','P. Borne');
INSERT INTO autor(IdAutor,Autor)VALUES('100003','J. Vignes');
INSERT INTO autor(IdAutor,Autor)VALUES('100004','Saydí María Negron Romero');
INSERT INTO autor(IdAutor,Autor)VALUES('100005','Brigette Tasha Hyacinth');
INSERT INTO autor(IdAutor,Autor)VALUES('100006','University of Exeter, UK');
INSERT INTO autor(IdAutor,Autor)VALUES('100007','IEEE Robotics and automation society');
INSERT INTO autor(IdAutor,Autor)VALUES('100008','Carlos Ojeda Díaz');
INSERT INTO autor(IdAutor,Autor)VALUES('100009','International Federation Of Automatic Control');
INSERT INTO autor(IdAutor,Autor)VALUES('100010','Microsoft Press');
INSERT INTO autor(IdAutor,Autor)VALUES('100011','Cornell University');
INSERT INTO autor(IdAutor,Autor)VALUES('100012','Johannes Kepler University Linz');
INSERT INTO autor(IdAutor,Autor)VALUES('100013','IEEE');
INSERT INTO autor(IdAutor,Autor)VALUES('100014','James A. Payne');
INSERT INTO autor(IdAutor,Autor)VALUES('100015','José Mompin Pobiet');
INSERT INTO autor(IdAutor,Autor)VALUES('100016','Paolo Rocco');
INSERT INTO autor(IdAutor,Autor)VALUES('100017','Chris H. Pappas');
INSERT INTO autor(IdAutor,Autor)VALUES('100018','Sergio Rinaldi E Lorenzo Farina');
INSERT INTO autor(IdAutor,Autor)VALUES('100019','William Ipanaqué Alama');
INSERT INTO autor(IdAutor,Autor)VALUES('100020','William H. Murray');
INSERT INTO autor(IdAutor,Autor)VALUES('100021','Edia Borland');
INSERT INTO autor(IdAutor,Autor)VALUES('100022','A. Valentina');
INSERT INTO autor(IdAutor,Autor)VALUES('100023','E. Giovanna');
INSERT INTO autor(IdAutor,Autor)VALUES('100024','Nebendahl');
INSERT INTO autor(IdAutor,Autor)VALUES('100025','Jie Cheng');
INSERT INTO autor(IdAutor,Autor)VALUES('100026','Ron J. Patton');
INSERT INTO autor(IdAutor,Autor)VALUES('100027','Wen C. Lin');
INSERT INTO autor(IdAutor,Autor)VALUES('100028','Electronics and Automatic Department, University of Piura');
INSERT INTO autor(IdAutor,Autor)VALUES('100029','I. Scott MacKEnzie');
INSERT INTO autor(IdAutor,Autor)VALUES('100030','Javier Sotomayor Moriano');
INSERT INTO autor(IdAutor,Autor)VALUES('100031','Carlos Gustavo Peréz Zuñiga');
INSERT INTO autor(IdAutor,Autor)VALUES('100032','Raul Rivas Peréz');
INSERT INTO autor(IdAutor,Autor)VALUES('100033','European Control Association (EUCA)');
INSERT INTO autor(IdAutor,Autor)VALUES('100034','Ann L. Winblad');
INSERT INTO autor(IdAutor,Autor)VALUES('100035','Samuel D. Edwards');
INSERT INTO autor(IdAutor,Autor)VALUES('100036','David R. King');
INSERT INTO autor(IdAutor,Autor)VALUES('100037','Rex Jaeschke');
INSERT INTO autor(IdAutor,Autor)VALUES('100038','Rodnay Zaks');
INSERT INTO autor(IdAutor,Autor)VALUES('100039','Ray Duncan');
INSERT INTO autor(IdAutor,Autor)VALUES('100040','A.D Pouliezos');
INSERT INTO autor(IdAutor,Autor)VALUES('100041','G.S. Stavrakakis');
INSERT INTO autor(IdAutor,Autor)VALUES('100042','S. Sebastian');
INSERT INTO autor(IdAutor,Autor)VALUES('100043','Tarik Ozkul');
INSERT INTO autor(IdAutor,Autor)VALUES('100044','Shem Tov Levi');
INSERT INTO autor(IdAutor,Autor)VALUES('100045','Ashok K. Agrawala');
INSERT INTO autor(IdAutor,Autor)VALUES('100046','Bernard Friedland');
INSERT INTO autor(IdAutor,Autor)VALUES('100047','M. Sc. Antonio J. Salvá Pando');
INSERT INTO autor(IdAutor,Autor)VALUES('100048','A. E. Fitzgerlad, SC. D.');
INSERT INTO autor(IdAutor,Autor)VALUES('100049','David. E. Higginbotham, S.M');
INSERT INTO autor(IdAutor,Autor)VALUES('100050','Arvin Gravel, Sc. D.');
INSERT INTO autor(IdAutor,Autor)VALUES('100051','CEAC');
INSERT INTO autor(IdAutor,Autor)VALUES('100052','Wolfgang Weiske');
INSERT INTO autor(IdAutor,Autor)VALUES('100053','Thomas L. Floyd');
INSERT INTO autor(IdAutor,Autor)VALUES('100054','J. David Irwin');
INSERT INTO autor(IdAutor,Autor)VALUES('100055','Tattamangalam R. Padmanabhan');
INSERT INTO autor(IdAutor,Autor)VALUES('100056','Paolo Bernardi');
INSERT INTO autor(IdAutor,Autor)VALUES('100057','Apolo Reali');
INSERT INTO autor(IdAutor,Autor)VALUES('100058','Günther Malhke');
INSERT INTO autor(IdAutor,Autor)VALUES('100059','Peter Gössing');
INSERT INTO autor(IdAutor,Autor)VALUES('100060','Paolo Mandarin');
INSERT INTO autor(IdAutor,Autor)VALUES('100061','McGraw-Hill');
INSERT INTO autor(IdAutor,Autor)VALUES('100062','Noel M. Morris');
INSERT INTO autor(IdAutor,Autor)VALUES('100063','A. Bertuzzi');
INSERT INTO autor(IdAutor,Autor)VALUES('100064','A. Gandolfi');
INSERT INTO autor(IdAutor,Autor)VALUES('100065','A. Germani');
INSERT INTO autor(IdAutor,Autor)VALUES('100066','U. Tieze Ch. Schenk');
INSERT INTO autor(IdAutor,Autor)VALUES('100067','Guido Guardabassi');
INSERT INTO autor(IdAutor,Autor)VALUES('100068','National Instruments');
INSERT INTO autor(IdAutor,Autor)VALUES('100069','Austin Lesea ');
INSERT INTO autor(IdAutor,Autor)VALUES('100070','Jacob Millman');
INSERT INTO autor(IdAutor,Autor)VALUES('100071','Christos C. Halkias');
INSERT INTO autor(IdAutor,Autor)VALUES('100072','Buzzeti F.');
INSERT INTO autor(IdAutor,Autor)VALUES('100073','Grassini Raffaglio E.');
INSERT INTO autor(IdAutor,Autor)VALUES('100074','David K. Ferry');
INSERT INTO autor(IdAutor,Autor)VALUES('100075','Vasconi Ajroldi A.');
INSERT INTO autor(IdAutor,Autor)VALUES('100076','Gottfried Möltgen');
INSERT INTO autor(IdAutor,Autor)VALUES('100077','Jerry D. Gibson');
INSERT INTO autor(IdAutor,Autor)VALUES('100078','The Math Works Inc.');
INSERT INTO autor(IdAutor,Autor)VALUES('100079','The Engineering Staff of Analog Devices, Inc');
INSERT INTO autor(IdAutor,Autor)VALUES('100080','Hans Grob');
INSERT INTO autor(IdAutor,Autor)VALUES('100081','G. Da Rios');
INSERT INTO autor(IdAutor,Autor)VALUES('100082','S. Rinelli');
INSERT INTO autor(IdAutor,Autor)VALUES('100083','J. C.Gille');
INSERT INTO autor(IdAutor,Autor)VALUES('100084','P. Decaulne');
INSERT INTO autor(IdAutor,Autor)VALUES('100085','M. Pelegrin');
INSERT INTO autor(IdAutor,Autor)VALUES('100086','The institution of Electrical Engineers');
INSERT INTO autor(IdAutor,Autor)VALUES('100087','G. Ferraté');
INSERT INTO autor(IdAutor,Autor)VALUES('100088','Thomas G. Beckwith');
INSERT INTO autor(IdAutor,Autor)VALUES('100089','N. Lewis Buck');
INSERT INTO autor(IdAutor,Autor)VALUES('100090','Massimiliano Petternella');
INSERT INTO autor(IdAutor,Autor)VALUES('100091','M. Bertolaccini');
INSERT INTO autor(IdAutor,Autor)VALUES('100092','C.Bussolati');
INSERT INTO autor(IdAutor,Autor)VALUES('100093','P.F. Manfredi');
INSERT INTO autor(IdAutor,Autor)VALUES('100094','T. Perales Benito');
INSERT INTO autor(IdAutor,Autor)VALUES('100095','J. G. Brennan');
INSERT INTO autor(IdAutor,Autor)VALUES('100096','J. R. Butters');
INSERT INTO autor(IdAutor,Autor)VALUES('100097','Roberto Viteli');
INSERT INTO autor(IdAutor,Autor)VALUES('100098','N. D. Cowell');
INSERT INTO autor(IdAutor,Autor)VALUES('100099','A. E. V. Lilly');
INSERT INTO autor(IdAutor,Autor)VALUES('100100','Miroliubov');
INSERT INTO autor(IdAutor,Autor)VALUES('100101','Timoshenko');
INSERT INTO autor(IdAutor,Autor)VALUES('100102','Young');
INSERT INTO autor(IdAutor,Autor)VALUES('100103','W. Nash');
INSERT INTO autor(IdAutor,Autor)VALUES('100104','Feodosiev');
INSERT INTO autor(IdAutor,Autor)VALUES('100105','Singer');
INSERT INTO autor(IdAutor,Autor)VALUES('100106','Katsuhiko Ogata');
INSERT INTO autor(IdAutor,Autor)VALUES('100107','Charles E. Rohrs');
INSERT INTO autor(IdAutor,Autor)VALUES('100108','James L. Melsa');
INSERT INTO autor(IdAutor,Autor)VALUES('100109','Donald G. Schultz');
INSERT INTO autor(IdAutor,Autor)VALUES('100110','A. Eli Nisenfeld');
INSERT INTO autor(IdAutor,Autor)VALUES('100111','Steven L. Mandell');
INSERT INTO autor(IdAutor,Autor)VALUES('100112','Jorge Díaz Mosto');
INSERT INTO autor(IdAutor,Autor)VALUES('100113','H. Stapelfeldt');
INSERT INTO autor(IdAutor,Autor)VALUES('100114','Omega');
INSERT INTO autor(IdAutor,Autor)VALUES('100115','F.Khorrami ');
INSERT INTO autor(IdAutor,Autor)VALUES('100116','P. Krishnamurthy');
INSERT INTO autor(IdAutor,Autor)VALUES('100117','H.Melkote');
INSERT INTO autor(IdAutor,Autor)VALUES('100118','H. teuchert');
INSERT INTO autor(IdAutor,Autor)VALUES('100119','Dr. Jose Ma Vdal Llenas');
INSERT INTO autor(IdAutor,Autor)VALUES('100120','T. D. Towers');
INSERT INTO autor(IdAutor,Autor)VALUES('100121','H. Trenkmann');
INSERT INTO autor(IdAutor,Autor)VALUES('100122','A. von Königslöw');
INSERT INTO autor(IdAutor,Autor)VALUES('100123','Alberto Isidori');
INSERT INTO autor(IdAutor,Autor)VALUES('100124','Alfred Holzt');
INSERT INTO autor(IdAutor,Autor)VALUES('100125','Alfred Richter');
INSERT INTO autor(IdAutor,Autor)VALUES('100126','Hans Teuchert');
INSERT INTO autor(IdAutor,Autor)VALUES('100127','Claudio Maffezzoni');
INSERT INTO autor(IdAutor,Autor)VALUES('100128','Juan Corrales Martín');
INSERT INTO autor(IdAutor,Autor)VALUES('100129','Hans von Beeren');
INSERT INTO autor(IdAutor,Autor)VALUES('100130','Alfredo A. Nuñez');
INSERT INTO autor(IdAutor,Autor)VALUES('100131','Doris A. Sáez');
INSERT INTO autor(IdAutor,Autor)VALUES('100132','Cristián E. Cortés');
INSERT INTO autor(IdAutor,Autor)VALUES('100133','Thomas E. Kissell');
INSERT INTO autor(IdAutor,Autor)VALUES('100134','Karl J. Astrom');
INSERT INTO autor(IdAutor,Autor)VALUES('100135','Bjorn Wittenmark');
INSERT INTO autor(IdAutor,Autor)VALUES('100136','Kristian N. Hagen');
INSERT INTO autor(IdAutor,Autor)VALUES('100137','PromPerú');
INSERT INTO autor(IdAutor,Autor)VALUES('100138','J. Gary Reid');
INSERT INTO autor(IdAutor,Autor)VALUES('100139','John P.Bentley');
INSERT INTO autor(IdAutor,Autor)VALUES('100140','Julián Flores Esnal');
INSERT INTO autor(IdAutor,Autor)VALUES('100141','Mario García Sanz');
INSERT INTO autor(IdAutor,Autor)VALUES('100142','Vladimir Kucera');
INSERT INTO autor(IdAutor,Autor)VALUES('100143','Tagun Über');
INSERT INTO autor(IdAutor,Autor)VALUES('100144','John R. Rice');
INSERT INTO autor(IdAutor,Autor)VALUES('100145','William L.Luyben');
INSERT INTO autor(IdAutor,Autor)VALUES('100146','Aidan ODwyer');
INSERT INTO autor(IdAutor,Autor)VALUES('100147','Muhammad H. Rashid');
INSERT INTO autor(IdAutor,Autor)VALUES('100148','Emmanuel Torquebiau');
INSERT INTO autor(IdAutor,Autor)VALUES('100149','Jorge Chau');
INSERT INTO autor(IdAutor,Autor)VALUES('100150','Jaime Lau');
INSERT INTO autor(IdAutor,Autor)VALUES('100151','Jürgen Röttger');
INSERT INTO autor(IdAutor,Autor)VALUES('100152','Eggers');
INSERT INTO autor(IdAutor,Autor)VALUES('100153','Gregroy');
INSERT INTO autor(IdAutor,Autor)VALUES('100154','Halsey');
INSERT INTO autor(IdAutor,Autor)VALUES('100155','Rabinovish');
INSERT INTO autor(IdAutor,Autor)VALUES('100156','Sergio Bittanti');
INSERT INTO autor(IdAutor,Autor)VALUES('100157','Nicola Schiavoni');
INSERT INTO autor(IdAutor,Autor)VALUES('100158','Arturo Locatelli');
INSERT INTO autor(IdAutor,Autor)VALUES('100159','Giorgio Guariso');
INSERT INTO autor(IdAutor,Autor)VALUES('100160','Eliot Laniado');
INSERT INTO autor(IdAutor,Autor)VALUES('100161','Sergio Rinaldi');
INSERT INTO autor(IdAutor,Autor)VALUES('100162','Constantine H. Houpis');
INSERT INTO autor(IdAutor,Autor)VALUES('100163','Gary B. Lamont');
INSERT INTO autor(IdAutor,Autor)VALUES('100164','Kumpati S. Narendra ');
INSERT INTO autor(IdAutor,Autor)VALUES('100165','Anuradha M. Annaswamy');
INSERT INTO autor(IdAutor,Autor)VALUES('100166','J. D. Perkins');
INSERT INTO autor(IdAutor,Autor)VALUES('100167','Antonio Ruberti');
INSERT INTO autor(IdAutor,Autor)VALUES('100168','Otto Leidinger');
INSERT INTO autor(IdAutor,Autor)VALUES('100169','Ross Barmish');
INSERT INTO autor(IdAutor,Autor)VALUES('100170','Giorgio Quazza');
INSERT INTO autor(IdAutor,Autor)VALUES('100171','Eduardo Ayesa Iturrate');
INSERT INTO autor(IdAutor,Autor)VALUES('100172','R. Berber');
INSERT INTO autor(IdAutor,Autor)VALUES('100173','Page S. Buckley');
INSERT INTO autor(IdAutor,Autor)VALUES('100174','Joseph P. Shunta');
INSERT INTO autor(IdAutor,Autor)VALUES('100175','Jeffrey C. Kantor');
INSERT INTO autor(IdAutor,Autor)VALUES('100176','Carlos E. Garcia');
INSERT INTO autor(IdAutor,Autor)VALUES('100177','Brice Carnahan');
INSERT INTO autor(IdAutor,Autor)VALUES('100178','J. E. Rijnsdorp');
INSERT INTO autor(IdAutor,Autor)VALUES('100179','J. F. MacGregor');
INSERT INTO autor(IdAutor,Autor)VALUES('100180','B.D. Tyreus');
INSERT INTO autor(IdAutor,Autor)VALUES('100181','T. Takamatsu');
INSERT INTO autor(IdAutor,Autor)VALUES('100182','Vibro Technolog S. R. LTDA');
INSERT INTO autor(IdAutor,Autor)VALUES('100183','H. C. Rodrigues');
INSERT INTO autor(IdAutor,Autor)VALUES('100184','J. Herskovits');
INSERT INTO autor(IdAutor,Autor)VALUES('100185','C. M. Mota Soares');
INSERT INTO autor(IdAutor,Autor)VALUES('100186','J. M. Guedes');
INSERT INTO autor(IdAutor,Autor)VALUES('100187','A. L. Araújo');
INSERT INTO autor(IdAutor,Autor)VALUES('100188','J. O. Folgado');
INSERT INTO autor(IdAutor,Autor)VALUES('100189','F. Moleiro');
INSERT INTO autor(IdAutor,Autor)VALUES('100190','J. F. A. Madeira');
INSERT INTO autor(IdAutor,Autor)VALUES('100191','Eugenio López Aldea');
INSERT INTO autor(IdAutor,Autor)VALUES('100192','Alejandro Vera Lázaro');
INSERT INTO autor(IdAutor,Autor)VALUES('100193','Paolo Aliverti');
INSERT INTO autor(IdAutor,Autor)VALUES('100194','Rubén Beiroa Mosquera');
INSERT INTO autor(IdAutor,Autor)VALUES('100195','Carl-Fedrik Mandenius ');
INSERT INTO autor(IdAutor,Autor)VALUES('100196','Nigel J. Titchener-Hooker');
INSERT INTO autor(IdAutor,Autor)VALUES('100197','Graciano Calderón Barrera');
INSERT INTO autor(IdAutor,Autor)VALUES('100198','Jaime Arango Cabarcas');
INSERT INTO autor(IdAutor,Autor)VALUES('100199','Adriana Gómez Hoyos');
INSERT INTO autor(IdAutor,Autor)VALUES('100200','Agustín Jiménez Avelló');
INSERT INTO autor(IdAutor,Autor)VALUES('100201','Eduardo Jiménez Moreno');
INSERT INTO autor(IdAutor,Autor)VALUES('100202','Sigurd Skogestad');
INSERT INTO autor(IdAutor,Autor)VALUES('100203','Ian Postlethwaite');
INSERT INTO autor(IdAutor,Autor)VALUES('100204','J. R. Leigh');
INSERT INTO autor(IdAutor,Autor)VALUES('100205','Arturo Rojas Moreno');
INSERT INTO autor(IdAutor,Autor)VALUES('100206','F. G. Shinskey');
INSERT INTO autor(IdAutor,Autor)VALUES('100207','Chandra Gopala Rao');
INSERT INTO autor(IdAutor,Autor)VALUES('100208','J. M. Maciejowski');
INSERT INTO autor(IdAutor,Autor)VALUES('100209','Jesús Fraile Mora');
INSERT INTO autor(IdAutor,Autor)VALUES('100210','Pedro García Gutiérrez');
INSERT INTO autor(IdAutor,Autor)VALUES('100211','Jesús Fraile Ardanuy');
INSERT INTO autor(IdAutor,Autor)VALUES('100212','');
INSERT INTO autor(IdAutor,Autor)VALUES('100213','María del Mar Castilla');
INSERT INTO autor(IdAutor,Autor)VALUES('100214','José Domingo Álvarez');
INSERT INTO autor(IdAutor,Autor)VALUES('100215','Francisco Rodríguez');
INSERT INTO autor(IdAutor,Autor)VALUES('100216','Manuel Bernguel');
INSERT INTO autor(IdAutor,Autor)VALUES('100217','Piotr Tatjewski');
INSERT INTO autor(IdAutor,Autor)VALUES('100218','Basil Kouvaritakis');
INSERT INTO autor(IdAutor,Autor)VALUES('100219','Mark Cannon');
INSERT INTO autor(IdAutor,Autor)VALUES('100220','Jean-Pierre Corriou');
INSERT INTO autor(IdAutor,Autor)VALUES('100221','Simon Haykin');
INSERT INTO autor(IdAutor,Autor)VALUES('100222','Luis Basañez Villaluenga');
INSERT INTO autor(IdAutor,Autor)VALUES('100223','Pere Caminal Magrans');
INSERT INTO autor(IdAutor,Autor)VALUES('100224','Pablo Parra Rosero');
INSERT INTO autor(IdAutor,Autor)VALUES('100225','Jaime E. Luyo');
INSERT INTO autor(IdAutor,Autor)VALUES('100226','Fernando S. Merchán');
INSERT INTO autor(IdAutor,Autor)VALUES('100227','Thomas Kailath');
INSERT INTO autor(IdAutor,Autor)VALUES('100228','Chi-Tsong Chen');
INSERT INTO autor(IdAutor,Autor)VALUES('100229','Peter Rein');
INSERT INTO autor(IdAutor,Autor)VALUES('100230','Univerisdad de Navarra');
INSERT INTO autor(IdAutor,Autor)VALUES('100231','Francisco Vázques');
INSERT INTO autor(IdAutor,Autor)VALUES('100232','Jorge Jiménez');
INSERT INTO autor(IdAutor,Autor)VALUES('100233','Juan Garrido');
INSERT INTO autor(IdAutor,Autor)VALUES('100234','Antonio Belmonte');
INSERT INTO autor(IdAutor,Autor)VALUES('100235','Rafael Estartús');
INSERT INTO autor(IdAutor,Autor)VALUES('100236','Pablo Pérez Sánchez');
INSERT INTO autor(IdAutor,Autor)VALUES('100237','Raymond Chang');
INSERT INTO autor(IdAutor,Autor)VALUES('100238','Universidad de Piura');
INSERT INTO autor(IdAutor,Autor)VALUES('100239','Genara Castillo');
INSERT INTO autor(IdAutor,Autor)VALUES('100240','Norman B. Haaser');
INSERT INTO autor(IdAutor,Autor)VALUES('100241','Joseph  P. La Salle');
INSERT INTO autor(IdAutor,Autor)VALUES('100242','Joseph P. Sullivan');
INSERT INTO autor(IdAutor,Autor)VALUES('100243','Jorge Nocedal Stephen ');
INSERT INTO autor(IdAutor,Autor)VALUES('100244','J. Wright');
INSERT INTO autor(IdAutor,Autor)VALUES('100245','José Ramón Perán Gonzalez');
INSERT INTO autor(IdAutor,Autor)VALUES('100246','José Santiváñez Marín');
INSERT INTO autor(IdAutor,Autor)VALUES('100247','Erbert Taub');
INSERT INTO autor(IdAutor,Autor)VALUES('100248','Donald Schilling');
INSERT INTO autor(IdAutor,Autor)VALUES('100249','John P. Hayes');
INSERT INTO autor(IdAutor,Autor)VALUES('100250','Christopher G. Relf');
INSERT INTO autor(IdAutor,Autor)VALUES('100251','Jeff Weigant');
INSERT INTO autor(IdAutor,Autor)VALUES('100252','John Blankenship');
INSERT INTO autor(IdAutor,Autor)VALUES('100253','Samuel Mishal');
INSERT INTO autor(IdAutor,Autor)VALUES('100254','Fred Eady');
INSERT INTO autor(IdAutor,Autor)VALUES('100255','David B. Makofske');
INSERT INTO autor(IdAutor,Autor)VALUES('100256','Michael J. Donahoo');
INSERT INTO autor(IdAutor,Autor)VALUES('100257','Kenneth L. Calvert');
INSERT INTO autor(IdAutor,Autor)VALUES('100258','M. H. Hamza');
INSERT INTO autor(IdAutor,Autor)VALUES('100259','Jan J. Tuma');
INSERT INTO autor(IdAutor,Autor)VALUES('100260','R. K. Munshi');
INSERT INTO autor(IdAutor,Autor)VALUES('100261','Instituto General de Investigación de la Universidad Nacional de Ingeniería');
INSERT INTO autor(IdAutor,Autor)VALUES('100262','V. Ionescu');
INSERT INTO autor(IdAutor,Autor)VALUES('100263','D. Popescu');
INSERT INTO autor(IdAutor,Autor)VALUES('100264','César Angulo Bustíos');
INSERT INTO autor(IdAutor,Autor)VALUES('100265','Tammy Noergaard');
INSERT INTO autor(IdAutor,Autor)VALUES('100266','Valeriy Labunets');
INSERT INTO autor(IdAutor,Autor)VALUES('100267','Ekaterina Ostheimer');
INSERT INTO autor(IdAutor,Autor)VALUES('100268','Lingfeng Wang');
INSERT INTO autor(IdAutor,Autor)VALUES('100269','Kay Chen Tan');
INSERT INTO autor(IdAutor,Autor)VALUES('100270','Wolfgang Weidinger');
INSERT INTO autor(IdAutor,Autor)VALUES('100271','Hamid A. Toliyat');
INSERT INTO autor(IdAutor,Autor)VALUES('100272','Steven G. Campbell');
INSERT INTO autor(IdAutor,Autor)VALUES('100273','Siemens');
INSERT INTO autor(IdAutor,Autor)VALUES('100274','Dimitrios Hristu-Varsakelis');
INSERT INTO autor(IdAutor,Autor)VALUES('100275','William S. Levine');
INSERT INTO autor(IdAutor,Autor)VALUES('100276','Jairo Espinosa');
INSERT INTO autor(IdAutor,Autor)VALUES('100277','Joos Vanderwalle');
INSERT INTO autor(IdAutor,Autor)VALUES('100278','Vincent Wertz');
INSERT INTO autor(IdAutor,Autor)VALUES('100279','Pong P. Chu');
INSERT INTO autor(IdAutor,Autor)VALUES('100280','Steve Furber');
INSERT INTO autor(IdAutor,Autor)VALUES('100281','Jean Praninskas');
INSERT INTO autor(IdAutor,Autor)VALUES('100282','Boson Park');
INSERT INTO autor(IdAutor,Autor)VALUES('100283','Renfu Lu');
INSERT INTO autor(IdAutor,Autor)VALUES('100284','Ernesto O. Doebelin');
INSERT INTO autor(IdAutor,Autor)VALUES('100285','Jan Faggerberg');
INSERT INTO autor(IdAutor,Autor)VALUES('100286','David C. Mowery');
INSERT INTO autor(IdAutor,Autor)VALUES('100287','Richard R. Nelson');
INSERT INTO autor(IdAutor,Autor)VALUES('100288','Autodesk');
INSERT INTO autor(IdAutor,Autor)VALUES('100289','Plessey Semiconductors');
INSERT INTO autor(IdAutor,Autor)VALUES('100290','Roland Wernecke');
INSERT INTO autor(IdAutor,Autor)VALUES('100291','Jan Wernecke');
INSERT INTO autor(IdAutor,Autor)VALUES('100292','Vyacheslav V. Komarov');
INSERT INTO autor(IdAutor,Autor)VALUES('100293','Gordon Clarke Deon Reynders');
INSERT INTO autor(IdAutor,Autor)VALUES('100294','Xilinx');
INSERT INTO autor(IdAutor,Autor)VALUES('100295','Pitagora Editrice Bologna');
INSERT INTO autor(IdAutor,Autor)VALUES('100296','Dave van Ess');
INSERT INTO autor(IdAutor,Autor)VALUES('100297','Rafael López Aliaga Cazorla');
INSERT INTO autor(IdAutor,Autor)VALUES('100298','Rosane F. Schwan');
INSERT INTO autor(IdAutor,Autor)VALUES('100299','Graham H. Fleet');
INSERT INTO autor(IdAutor,Autor)VALUES('100300','Maciej Kranz');
INSERT INTO autor(IdAutor,Autor)VALUES('100301','Carlos Silva Cárdenas');
INSERT INTO autor(IdAutor,Autor)VALUES('100302','Eduardo Ismodes Cascón');
INSERT INTO autor(IdAutor,Autor)VALUES('100303','Bei Wang');
INSERT INTO autor(IdAutor,Autor)VALUES('100304','Christopher Lan');
INSERT INTO autor(IdAutor,Autor)VALUES('100305','Society for Industrial and Applied Mathematics');
INSERT INTO autor(IdAutor,Autor)VALUES('100306','Rodolfo Rodríguez');
INSERT INTO autor(IdAutor,Autor)VALUES('100307','Roxana Fernández');
INSERT INTO autor(IdAutor,Autor)VALUES('100308','Giuseppe Tanzella-Nitti');
INSERT INTO autor(IdAutor,Autor)VALUES('100309','Andrzej Janczak');
INSERT INTO autor(IdAutor,Autor)VALUES('100310','Riccardo Marino');
INSERT INTO autor(IdAutor,Autor)VALUES('100311','Patrizio Tomei');
INSERT INTO autor(IdAutor,Autor)VALUES('100312','Cristiano M. Verrelli');
INSERT INTO autor(IdAutor,Autor)VALUES('100313','Dennis Silage');
INSERT INTO autor(IdAutor,Autor)VALUES('100314','Jean-Pierre Deschamps');
INSERT INTO autor(IdAutor,Autor)VALUES('100315','Gustavo D. Sutter');
INSERT INTO autor(IdAutor,Autor)VALUES('100316','Enrique Cantó');
INSERT INTO autor(IdAutor,Autor)VALUES('100317','Ernest O. Doebelin');
INSERT INTO autor(IdAutor,Autor)VALUES('100318','Donald G. Bailey');
INSERT INTO autor(IdAutor,Autor)VALUES('100319','Salvador Bernal');
INSERT INTO autor(IdAutor,Autor)VALUES('100320','Olle I. Elgerd');
INSERT INTO autor(IdAutor,Autor)VALUES('100321','Alfio Quarteroni');
INSERT INTO autor(IdAutor,Autor)VALUES('100322','Fausto Saleri');
INSERT INTO autor(IdAutor,Autor)VALUES('100323','Soteris A. Kalogirou');
INSERT INTO autor(IdAutor,Autor)VALUES('100324','Luigi del Re');
INSERT INTO autor(IdAutor,Autor)VALUES('100325','Bashir M. Al-Hashimi');
INSERT INTO autor(IdAutor,Autor)VALUES('100326','Holly Moore');
INSERT INTO autor(IdAutor,Autor)VALUES('100327','Microsoft Corporation');
INSERT INTO autor(IdAutor,Autor)VALUES('100328','H. L. Trentelman');
INSERT INTO autor(IdAutor,Autor)VALUES('100329','J. C. Willems');
INSERT INTO autor(IdAutor,Autor)VALUES('100330','Shoichiro Nakamura');
INSERT INTO autor(IdAutor,Autor)VALUES('100331','Eric Schmidt');
INSERT INTO autor(IdAutor,Autor)VALUES('100332','Jonathan Rosenberg');
INSERT INTO autor(IdAutor,Autor)VALUES('100333','Alan Eagle');
INSERT INTO autor(IdAutor,Autor)VALUES('100334','Francisco Sagasti');
INSERT INTO autor(IdAutor,Autor)VALUES('100335','Alfredo Torres');
INSERT INTO autor(IdAutor,Autor)VALUES('100336','Rama Estudiantil IEEE');
INSERT INTO autor(IdAutor,Autor)VALUES('100337','Reed Hastings');
INSERT INTO autor(IdAutor,Autor)VALUES('100338','Erin Meyer');
INSERT INTO autor(IdAutor,Autor)VALUES('100339','Scott Galloway');
INSERT INTO autor(IdAutor,Autor)VALUES('100340','Francisco Fernandez Carvajal');
INSERT INTO autor(IdAutor,Autor)VALUES('100341','Louis de Wohl');
INSERT INTO autor(IdAutor,Autor)VALUES('100342','Frank Dale Morgan');
INSERT INTO autor(IdAutor,Autor)VALUES('100343','Rama Rao V.N.');
INSERT INTO autor(IdAutor,Autor)VALUES('100344','Darrell Coles');
INSERT INTO autor(IdAutor,Autor)VALUES('100345','Przemyslaw Sliwinski');
INSERT INTO autor(IdAutor,Autor)VALUES('100346','Fei Hu');
INSERT INTO autor(IdAutor,Autor)VALUES('100347','Centro Nacional de Planeamiento Estratégico (CEPLAN)');
INSERT INTO autor(IdAutor,Autor)VALUES('100348','Panagiotis D. Christofides');
INSERT INTO autor(IdAutor,Autor)VALUES('100349','Jinfeng Liu');
INSERT INTO autor(IdAutor,Autor)VALUES('100350','David Muñoz de la Peña');
INSERT INTO autor(IdAutor,Autor)VALUES('100351','Syed Saad Azhar Ali');
INSERT INTO autor(IdAutor,Autor)VALUES('100352','T. Ogunfunmi');
INSERT INTO autor(IdAutor,Autor)VALUES('100353','Joao M. Lemos');
INSERT INTO autor(IdAutor,Autor)VALUES('100354','Rui Neves-Silva');
INSERT INTO autor(IdAutor,Autor)VALUES('100355','José M. Igreja');
INSERT INTO autor(IdAutor,Autor)VALUES('100356','S. Allen Broughton');
INSERT INTO autor(IdAutor,Autor)VALUES('100357','Kurt Bryan');
INSERT INTO autor(IdAutor,Autor)VALUES('100358','Lalo Magni');
INSERT INTO autor(IdAutor,Autor)VALUES('100359','Davide Martino Raimondo');
INSERT INTO autor(IdAutor,Autor)VALUES('100360','Frank Allgower');
INSERT INTO autor(IdAutor,Autor)VALUES('100361','Vladimir G. Ivancevic');
INSERT INTO autor(IdAutor,Autor)VALUES('100362','Tijana T. Ivancevic');
INSERT INTO autor(IdAutor,Autor)VALUES('100363','Robert Haber ');
INSERT INTO autor(IdAutor,Autor)VALUES('100364','Laszlo Keviczky');
INSERT INTO autor(IdAutor,Autor)VALUES('100365','Eusebio Ferrer');
INSERT INTO autor(IdAutor,Autor)VALUES('100366','Ramón García de Haro');
INSERT INTO autor(IdAutor,Autor)VALUES('100367','Mariano Artigas');
INSERT INTO autor(IdAutor,Autor)VALUES('100368','Juan José Sanguineti');
INSERT INTO autor(IdAutor,Autor)VALUES('100369','Kenneth K. Kuo');
INSERT INTO autor(IdAutor,Autor)VALUES('100370','Samuel Burns');
INSERT INTO autor(IdAutor,Autor)VALUES('100371','Bagher Jamali');
INSERT INTO autor(IdAutor,Autor)VALUES('100372','Hooshang Jazayeri-Rad');
INSERT INTO autor(IdAutor,Autor)VALUES('100373','Mohammad Ali Ghayyem');
INSERT INTO autor(IdAutor,Autor)VALUES('100374','Miguel-Ángel Martí García');
INSERT INTO autor(IdAutor,Autor)VALUES('100375','Luis Romera Oñate');
INSERT INTO autor(IdAutor,Autor)VALUES('100376','Luis Cano');
INSERT INTO autor(IdAutor,Autor)VALUES('100377','Oliveros F. Otero');
INSERT INTO autor(IdAutor,Autor)VALUES('100378','Joseph Ratzinger (Bemedicto XVI)');
INSERT INTO autor(IdAutor,Autor)VALUES('100379','Edizioni Ares - Milano');
INSERT INTO autor(IdAutor,Autor)VALUES('100380','Josemaría Escrivá');
INSERT INTO autor(IdAutor,Autor)VALUES('100381','Modesto Montoya');
INSERT INTO autor(IdAutor,Autor)VALUES('100382','B. M. Quartu');
INSERT INTO autor(IdAutor,Autor)VALUES('100383','Angel Luis Gonzalez');
INSERT INTO autor(IdAutor,Autor)VALUES('100384','Peter L. Lee');
INSERT INTO autor(IdAutor,Autor)VALUES('100385','C. K. Chui');
INSERT INTO autor(IdAutor,Autor)VALUES('100386','G. Chen');
INSERT INTO autor(IdAutor,Autor)VALUES('100387','Hans P.G.');
INSERT INTO autor(IdAutor,Autor)VALUES('100388','Ronald R. Mohler');
INSERT INTO autor(IdAutor,Autor)VALUES('100389','J. J. Bloem');
INSERT INTO autor(IdAutor,Autor)VALUES('100390','Ian F. Akyildiz');
INSERT INTO autor(IdAutor,Autor)VALUES('100391','Mehmet Can Vuran');
INSERT INTO autor(IdAutor,Autor)VALUES('100392','Panos J. Antsaklis');
INSERT INTO autor(IdAutor,Autor)VALUES('100393','Anthony N. Michel');
INSERT INTO autor(IdAutor,Autor)VALUES('100394','Denis Dochain');


-- si se van a agregar registros directamente a la DB hacerlo después de este comentario
