USE sac;

-- tabla libro
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('1','12TH World congress on scientific computation July 18-22 1988 (2)','7','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('2','Presenting Peru and Machupicchu','7','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('3','The future of leadership','7','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('4',"International Conference on control '96",'7','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('5',"12TH World congress on scientific computation July 18-22 1988 (1)",'7','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('6',"Robotics and automation Vol. 3",'7','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('7','Resistencia de materiales','7','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('8',"Organization of the preprints plenary papers authors' index Vol. 1",'7','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('9','Microsoft Visual C++ Part 1','7','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('10','Curso de capacitación para productores','7','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('11','Introduction to optimization','7','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('12','IEEE Signal Processing Magazine vol. 25 number 4','7','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('13','Introduction to simulation','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('14','Microprocesadores y microcomputadores','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('15','Algoritmi di controllo in posizione e forza per robot industriali: analisi teorica ed implementazione','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('16','Manual del microprocesador','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('17','I Sistemi lineari positivi: teoria e applicazioni','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('18','Redes de Petri','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('19','Analisi Numerica Metodi Modelli Applicazioni Valeriano Comincioli','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('20','International Conference on Automatic Control','6','1',2);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('21','European Control Conference 13','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('22','Real time Sistem Design','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('23','LabVIEW for Windows: Graphical Programming for Instrumentation','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('24','LabVIEW for Windows: Getting Started with LabVIEW for Windows','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('25','Robust Model-Based Fault Diagnosis for dynamic systems','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('26','Ponencias del XV congreso Latinoamericano de Control Automático 23-26 de Octubre 2012','6','1',2);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('27','Real time fault monitoring of industrial processes','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('28','Apuntes varios Servomecanismos Hidraulicos','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('29',"Introduzione alla teoria dell'identificazione parametrica dei sistemi lineari stocastici",'6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('30','Elementi di controllo digitale','6','1',2);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('31','Esercizi di analisi matematica 1 Parte 1','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('32','Turbo C 2.0 vol 2','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('33','Turbo C 2.0 Vol 1','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('34','Sistemas Expertos parte 2','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('35','Microprocessors: Fundamenatks & Aplications','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('36','The 8051 Microcontroller','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('37','Software orientado a Objetos','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('38','Solutions in C','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('39','Microsoft Visual C++ Vol 3','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('40','Programación del 6502','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('41','MSDOS Avanzado','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('42','Data Acquisition and Process control using personal o¿computers ','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('43','Control System Design An introduction to State-Space Methods','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('44','Acustica Submarina','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('45','Fundamentos de Ingenieria Eléctrica','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('46','Equipos Electrico-Mecánicos Industriales','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('47','Corriente trifásica','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('48','Principle of Electric Cricuits','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('49','Basic Engineering Circuit Analysis','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('50','Industrial Instrumentation Principles and Desing','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('51','Misure e Strumenti Electronici','6','1',2);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('52','Conductores de fibras ópticas','6','1',2);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('53','Teoria del Segnali','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('54','Electrónica Práctica','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('55','Problemas resuletos de electronica Industrial','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('56','Advanced Electronic Circuits','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('57',"Tecniche d'interfacciamento dei microprocessori",'6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('58','Solucionario Dispositivos y Circuitos Electrónicos','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('59','Semiconductors','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('60','Convertidores estáticos','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('61','Principles of Digital and Analog Communications ','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('62','Analog-Digital Conversion Handbook','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('63','Azionamenti electtrici di avanzamento per macchine utensili','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('64','Semafor!','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('65','Servo Sistemas Teoria y Calculo','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('66','Nonlinear predictive control theory and practice','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('67','Robotica industrial','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('68','Mehcnical Measurements','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('69','Electronica per Misure industriali','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('70','Medidores Digitales Instrumentación lineal y digital','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('71','Using MATLAB Version 5','6','1',2);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('72','Microsoft Visual C++: Run-Time Library Reference','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('73','Las Operaciones de la Ingeniería de los Alimentos','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('74','Industrial Evaporators','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('75','Computers and Data Processing','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('76','Algae: Nutrition, Pollution Control and Energy Sources','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('77','Fundamentos de la electrotecnia','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('78','Tablas universales Towers para selección de transistoreas','6','2',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('79','Esercizi di analisi matematica 1 Parte 2','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('80','Resistencia de materiales Problemas Selectos','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('81','Resistencia de materiales Ejercicios y Problemas','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('82','The temperature Handbook','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('83','Modeling and Adaptive Nonlinear Control of Electric Motors','6','1',2);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('84','Sistemai di Controllo','6','1',2);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('85','Controllo dei Generatori','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('86','Computer Controlled Systems','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('87','Peru: Beyond the Reforms','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('88','Sistemas Automáticos de Control: Control Digital','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('89','Introducción al Control Adaptativo','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('90','Strumentazione Industriale trasduttori e regalatori','6','1',2);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('91','Dinamica de sistemas','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('92','Sistemas de control lineal','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('93','Ténicas de las medidas eléctricas','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('94','Máquinas de corriente Continua','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('95','Máquinas de corriente Alterna Asincronas','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('96','Acumuladores elementos galvánicos galvanotecnia','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('97','Técnica de la iluminación elétrica','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('98','Fuerza y Motriz Tracción elétrica','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('99','Teoría, cálculo y construcción de transformadores','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('100','Técnica de la alta tensión','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('101','Telecomunicación por conductores ','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('102','Alta frecuencia y radiotecnia','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('103','Solutions manual Basic Engineering Circuit Analysis','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('104','Applications for programmable Controllers, Instrumentation and Process Control and Electrical Machines and Motor Controls','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('105','Signal processing toolbox for use with matlab','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('106','Robust Control toolbox for use with matlab','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('107','Hybrid Predictive control for dynamic transport problems','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('108','Linear system fundamentals','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('109','Sistemas de medición Principios y aplicaciones segunda edición','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('110','Analysis and design of discrete linear control systems','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('111','Practical Distillation control','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('112','Einsatz Von Mikroprozessoren in der Fluiddantriebstechnik','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('113','Matriz Computations & Mathematical Software','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('114','Handbook of PI and PID Controller Tuning Rules','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('115','Climate Change and Agricultire Worlwide','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('116','MST10','6','1',2);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('117','Fisicoquímica','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('118','Manual del usuario y referencia para el sistema operativo MS-DOS','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('119','Modellistica e controllo','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('120','Raccolta di Problemi di Controllo Ottimo','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('121','Controlli Automatici Parte 1','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('122','Analisi dei Sistemi Esercizi','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('123','Digital Control Systems','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('124','Sistemi di controllo','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('125','Teoria del sistemi','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('126','Controllo dei Processi','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('127','New Tools for Robustness of linear systems','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('128','Circuitos Microelectrónicos: análisis y diseño','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('129','Stable Adaptative Systems','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('130','Procesos Industriales','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('131','Methods of Model Based Process Control','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('132','Electrónica y Automática Industriales II','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('133','Chemical Process Control','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('134','Análisis Vibracional en el Mnatenimiento Predictivo','6','1',2);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('135','Interactions Between process design and process control','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('136','Estrategias de control avanzado','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('137','Design of distillation column control systems','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('138','Dynamics and control of chemical reactors, distillation columns and batch processes','6','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('139','Engineering Optimization IV','4','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('140','Arduino: Guía práctica de fundamentos y simulación','4','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('141','Manual de Arduino','4','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('142','Measurement, Monitoring, Modelling and Control of Bioprocesses','4','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('143','Cálculo diferencial Problemas Resuletos','4','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('144','Arduino, electrónica y programación con 100 ejercicios practicos','4','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('145','Ecuaciones diferenciales 1','4','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('146','Ecuaciones diferenciales para estudiantes de Ciencias e ingenierias','4','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('147','Multivariable Feedback Control: Analysis and Design','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('148','Control No Lineal Multivariable','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('149','Controlling Multivariable Pocesses','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('150','Multivariable Feedback Design','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('151','Discrete-Time Control Systems','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('152','Process Control: Theory and Applications','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('153','Adaptive Filter Theory second edition','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('154','Control digital. Problemas','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('155','Introducción al Control Óptimo','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('156','Applied Digital Control','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('157','Control Automático de procesos. Innovando los procesos productivos','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('158','Engineering for Storage of Fruits and Vegetables','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('159','Ingeniería de control. Aplicaciones con MATLAB','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('160','Comfort Control in Buildings','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('161','Advanced Control of Industrial Processes','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('162','Model Predictive Control','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('163','Análisis descriptivo de procesos industriales en ingeniería industrial','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('164','Tería de control automático','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('165','Linear systems','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('166','Linear System Theory and Design','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('167','Josemaría Escrivá de Balaguer y la Universidad','8','1',2);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('168','Introducción al Modelado y Simulación con EcosimPro','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('169','Docencia universitaria','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('170','guía universitaria. Guía para el profesor y el alumno','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('171','Asesoramiento personal universitario','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('172','Electronica Integrata Digitale','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('173','Cane Sugar Engineering','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('174','Diseño de Sistemas Digitales y Microprocesadores','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('175','Image Acquisition and Processing with LabVIEW','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('176','Creating Human Machine Interfaces Using Visual Basic','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('177','Libro Blanco de la Automatización y Control en la industria de la caña de azúcar','8','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('178','A Hardward Interfacing and Control Protocol','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('179','Hands-On ZigBee','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('180','TCP/IP Sockets in C#: Practical Guide for Programmers','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('181','Intelligent Systems and Control','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('182','Análisis Estructural Avanzado','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('183','TECNIA: Revista técnico científica','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('184','IFAC Conference on System Structure and Control','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('185','10th World Congress on Automatic Control Volume 6','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('186','Estadística','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('187','Embedded Systems Architecture','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('188','Modern Methods of Image Processing and Pattern Recognition, Part 1','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('189','Modern Industrial Automation Software Design: Principles and Real-World Examples','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('190','System Invastigation of Programmable Systems on Chip (PSoC)','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('191','DSP - Electromechanical Motion Control','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('192','Closed-Loop Control with SIMATIC S5','3','1',2);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('193','Handbook of Networked and Embedded Control Systems','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('194','Fuzzy Logic, Identification and Predictive Control','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('195','FPGA Prototyping by VHDL examples','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('196','ARM System-on-chip architecture','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('197','Rapid Review of English Grammar','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('198','Hyperspectral Imaging Technology in Food and Agriculture','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('199','Diseño y aplicación de sistemas de medición ','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('200','Control Predictivo: Una técnica para el futuro de la industria','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('201','The Oxford Handbook of Innovation','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('202','AutoCAD Land Development Desktop: Getting Started Guide','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('203','Data Converters and Voltage References IC Handbook','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('204','Control automático de procesos','3','1',2);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('205','Industrial Moisture and humidity measurement','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('206','Handbook of dielectric and thermal properties of materials at microwave frecuencies','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('207','Modern SCADA protocols','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('208','A hands-on guide to effective embedded design','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('209','Count Riccati and the early days of the riccati equation','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('210',"Autocad Land development Desktop: User's Guide",'3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('211','Learn digital design with PSOC a bit at a time','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('212','Oportunidades de inversión en el Perú','3','1',2);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('213','Cocoa and Coffe Fermentations','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('214','Internet of Things','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('215','Quinto Workshop Iberchip Memorias','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('216','Microalgae for Biofuel Production and CO2 Sequestration','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('217','Siam Review','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('218','Dendrocronología Básica','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('219','Pasión por la verdad: La responsabilidad del saber y la Universidad en el pensamiento de Juan Pablo II','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('220','Identification of Nonlinear Systems Using Neural Networks and Polynomial Models','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('221','Induction Motor Control Design','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('222','Embedded Design Using Programmable Gate Arrays','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('223','Guide to FPGA Implementation of Arithmetic Functions','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('224','Measurement Systems: Application and Design','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('225','Design for Embedded Image Processing on FPGAs','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('226','Mons. Josemaría Escrivá de Balaguer','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('227','Control Systems Theory','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('228','Scientific Computing with MATLAB and Octave','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('229','Solar Energy Engineering: Processes and Systems','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('230','Electrónica: serie apuntes','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('231','System-on-Chip: Next Generation Electronics','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('232','MATLAB para ingenieros ','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('233','Microsoft Visual C++: MFC Library Reference Part 2','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('234',"Microsft Visual C++: User's Guides",'3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('235','Essays on Control: Perspective in the Theory and its Applications','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('236','Análisis Numérico y Visualización Gráfica con MATLAB','3','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('237','How Google Works','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('238','Ciencia, Tecnología, Innovación','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('239','Opinión pública 1921-2021','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('240','INTERCON 2001','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('241','No rules rules: Netflix and the Culture of Reinvention','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('242','Four: El ADN secreto de amazon, apple, facebook y google','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('243','La Tiepidezza','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('244','El asalto del cielo','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('245','Data and Model in Engineering, Science and Business','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('246','Nonlinear System Identification by Haar Wavelets','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('247','Security and Privacy in Internet of Things (IoTs)','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('248','Plan Bicentenario: El Perú hacia el 2021','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('249','Networked and Distributed Predictive Control','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('250','Block Oriented Identification of Nonlinear Systems','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('251','Adaptive Nonlinear System Identification','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('252','Teoria della Predizione e del Filtraggio','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('253','Adaptive Control of Solar Energy Collector Systems','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('254','Discrete Fourier Analysis and Wavelets','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('255','Nonlinear Model Predictive Control','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('256','New Trends in Control Theory','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('257','Nonlinear System Identification - Input-Output Modeling Approach Vol. 1','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('258','Nonlinear System Identification - Input-Output Modeling Approach Vol. 2','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('259','Juan Pablo II. Pregonero de la Verdad (Vol. II)','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('260',"L'agire morale & le virtu",'1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('261','Filosofia della natura','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('262','Principles of combustion ','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('263','Python deep learning','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('264','Nonlinear identification using adaptive local linear neuro-fuzzy','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('265','La Serenidad: Una actitud ante el mundo','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('266','La actualidad del pensamiento cristiano','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('267','Juan Pablo II. Pregonero de la Verdad (Vol. I)','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('268','Cartas (I) Josémaría Escrivá de Balanguer: Obras Completas','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('269','La libertad en la familia','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('270','Jesús de Nazareth: desde la entrada en Jerusalén hasta la Resurrección','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('271','Preguiere','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('272','E Gesu che passa ','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('273','Políticas para impulsar la ciencia, la tecnología y la innovación tecnológica en el Perú','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('274','Dizionario dei sinonimi e dei contrari','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('275','Adaptive Control: selected solutions to accompany','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('276','Filosofia di dio','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('277','Nonlinear Process Control: Applications of Generic Model Control','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('278','Linear Systems and Optimal Control','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('279','Optimal Control with Engineering Applications','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('280','Nonlinear Systems (Vol. 1 Dynamics and Control)','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('281','Nonlinear Systems (Vol. 2 Applications to Bilinear Control)','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('282','System Identification Competition ','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('283','Wireless Sensor Networks','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('284','Linear Systems ','1','1',1);
INSERT INTO libro(IdLibro,Titulo,IdUbi,IdEstado,Cantidad)VALUES('285','Bioprocess Control','4','4',1);





-- si se van a agregar registros directamente a la DB hacerlo después de este comentario

