USE sac;

-- tabla titulo

INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('1','12TH World congress on scientific computation July 18-22 1988(2)','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('2','Presenting Peru and Machupicchu','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('3','The future of leadership','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('4','International Conference on control 96','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('5','12TH World congress on scientific computation July 18-22 1988(1)','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('6','Robotics and automation Vol. 3','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('7','Resistencia de materiales','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('8','Organization of the preprints plenary papers authors index Vol. 1','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('9','Microsoft Visual C++ Part 1','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('10','Curso de capacitación para productores','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('11','Introduction to optimization','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('12','IEEE Signal Processing Magazine vol. 25 number 4','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('13','Introduction to simulation','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('14','Microprocesadores y microcomputadores','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('15','Algoritmi di controllo in posizione e forza per robot industriali: analisi teorica ed implementazione','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('16','Manual del microprocesador','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('17','I Sistemi lineari positivi: teoria e applicazioni','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('18','Redes de Petri','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('19','Analisi Numerica Metodi Modelli Applicazioni Valeriano Comincioli','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('20','International Conference on Automatic Control','2');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('21','European Control Conference 13','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('22','Real time Sistem Design','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('23','LabVIEW for Windows: Graphical Programming for Instrumentation','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('24','LabVIEW for Windows: Getting Started with LabVIEW for Windows','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('25','Robust Model-Based Fault Diagnosis for dynamic systems','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('26','Ponencias del XV congreso Latinoamericano de Control Automático 23-26 de Octubre 2012','2');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('27','Real time fault monitoring of industrial processes','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('28','Apuntes varios Servomecanismos Hidraulicos','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('29','Introduzione alla teoria dell identificazione parametrica dei sistemi lineari stocastici','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('30','Elementi di controllo digitale','2');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('31','Esercizi di analisi matematica 1 Parte 1','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('32','Turbo C 2.0 vol 2','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('33','Turbo C 2.0 Vol 1','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('34','Sistemas Expertos parte 2','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('35','Microprocessors: Fundamenatks & Aplications','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('36','The 8051 Microcontroller','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('37','Software orientado a Objetos','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('38','Solutions in C','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('39','Microsoft Visual C++ Vol 3','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('40','Programación del 6502','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('41','MSDOS Avanzado','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('42','Data Acquisition and Process control using personal o¿computers ','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('43','Control System Design An introduction to State-Space Methods','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('44','Acustica Submarina','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('45','Fundamentos de Ingenieria Eléctrica','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('46','Equipos Electrico-Mecánicos Industriales','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('47','Corriente trifásica','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('48','Principle of Electric Cricuits','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('49','Basic Engineering Circuit Analysis','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('50','Industrial Instrumentation Principles and Desing','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('51','Misure e Strumenti Electronici','2');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('52','Conductores de fibras ópticas','2');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('53','Teoria del Segnali','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('54','Electrónica Práctica','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('55','Problemas resuletos de electronica Industrial','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('56','Advanced Electronic Circuits','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('57','Tecniche d interfacciamento dei microprocessori','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('58','Solucionario Dispositivos y Circuitos Electrónicos','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('59','Semiconductors','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('60','Convertidores estáticos','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('61','Principles of Digital and Analog Communications ','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('62','Analog-Digital Conversion Handbook','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('63','Azionamenti electtrici di avanzamento per macchine utensili','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('64','Semafor!','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('65','Servo Sistemas Teoria y Calculo','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('66','Nonlinear predictive control theory and practice','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('67','Robotica industrial','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('68','Mehcnical Measurements','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('69','Electronica per Misure industriali','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('70','Medidores Digitales Instrumentación lineal y digital','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('71','Using MATLAB Version 5','2');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('72','Microsoft Visual C++: Run-Time Library Reference','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('73','Las Operaciones de la Ingeniería de los Alimentos','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('74','Industrial Evaporators','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('75','Computers and Data Processing','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('76','Algae: Nutrition, Pollution Control and Energy Sources','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('77','Fundamentos de la electrotecnia','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('78','Tablas universales Towers para selección de transistoreas','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('79','Esercizi di analisi matematica 1 Parte 2','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('80','Resistencia de materiales Problemas Selectos','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('81','Resistencia de materiales Ejercicios y Problemas','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('82','The temperature Handbook','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('83','Modeling and Adaptive Nonlinear Control of Electric Motors','2');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('84','Sistemai di Controllo','2');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('85','Controllo dei Generatori','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('86','Computer Controlled Systems','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('87','Peru: Beyond the Reforms','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('88','Sistemas Automáticos de Control: Control Digital','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('89','Introducción al Control Adaptativo','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('90','Strumentazione Industriale trasduttori e regalatori','2');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('91','Dinamica de sistemas','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('92','Sistemas de control lineal','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('93','Ténicas de las medidas eléctricas','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('94','Máquinas de corriente Continua','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('95','Máquinas de corriente Alterna Asincronas','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('96','Acumuladores elementos galvánicos galvanotecnia','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('97','Técnica de la iluminación elétrica','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('98','Fuerza y Motriz Tracción elétrica','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('99','Teoría, cálculo y construcción de transformadores','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('100','Técnica de la alta tensión','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('101','Telecomunicación por conductores ','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('102','Alta frecuencia y radiotecnia','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('103','Solutions manual Basic Engineering Circuit Analysis','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('104','Applications for programmable Controllers, Instrumentation and Process Control and Electrical Machines and Motor Controls','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('105','Signal processing toolbox for use with matlab','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('106','Robust Control toolbox for use with matlab','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('107','Hybrid Predictive control for dynamic transport problems','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('108','Linear system fundamentals','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('109','Sistemas de medición Principios y aplicaciones segunda edición','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('110','Analysis and design of discrete linear control systems','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('111','Practical Distillation control','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('112','Einsatz Von Mikroprozessoren in der Fluiddantriebstechnik','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('113','Matriz Computations & Mathematical Software','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('114','Handbook of PI and PID Controller Tuning Rules','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('115','Climate Change and Agricultire Worlwide','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('116','MST10','2');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('117','Fisicoquímica','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('118','Manual del usuario y referencia para el sistema operativo MS-DOS','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('119','Modellistica e controllo','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('120','Raccolta di Problemi di Controllo Ottimo','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('121','Controlli Automatici Parte 1','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('122','Analisi dei Sistemi Esercizi','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('123','Digital Control Systems','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('124','Sistemi di controllo','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('125','Teoria del sistemi','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('126','Controllo dei Processi','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('127','New Tools for Robustness of linear systems','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('128','Circuitos Microelectrónicos: análisis y diseño','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('129','Stable Adaptative Systems','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('130','Procesos Industriales','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('131','Methods of Model Based Process Control','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('132','Electrónica y Automática Industriales II','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('133','Chemical Process Control','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('134','Análisis Vibracional en el Mnatenimiento Predictivo','2');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('135','Interactions Between process design and process control','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('136','Estrategias de control avanzado','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('137','Design of distillation column control systems','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('138','Dynamics and control of chemical reactors, distillation columns and batch processes','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('139','Engineering Optimization IV','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('140','Arduino: Guía práctica de fundamentos y simulación','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('141','Manual de Arduino','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('142','Measurement, Monitoring, Modelling and Control of Bioprocesses','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('143','Cálculo diferencial Problemas Resuletos','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('144','Arduino, electrónica y programación con 100 ejercicios practicos','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('145','Ecuaciones diferenciales 1','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('146','Ecuaciones diferenciales para estudiantes de Ciencias e ingenierias','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('147','Multivariable Feedback Control: Analysis and Design','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('148','Control No Lineal Multivariable','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('149','Controlling Multivariable Pocesses','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('150','Multivariable Feedback Design','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('151','Discrete-Time Control Systems','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('152','Process Control: Theory and Applications','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('153','Adaptive Filter Theory second edition','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('154','Control digital. Problemas','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('155','Introducción al Control Óptimo','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('156','Applied Digital Control','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('157','Control Automático de procesos. Innovando los procesos productivos','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('158','Engineering for Storage of Fruits and Vegetables','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('159','Ingeniería de control. Aplicaciones con MATLAB','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('160','Comfort Control in Buildings','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('161','Advanced Control of Industrial Processes','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('162','Model Predictive Control','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('163','Análisis descriptivo de procesos industriales en ingeniería industrial','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('164','Tería de control automático','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('165','Linear systems','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('166','Linear System Theory and Design','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('167','Josemaría Escrivá de Balaguer y la Universidad','2');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('168','Introducción al Modelado y Simulación con EcosimPro','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('169','Docencia universitaria','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('170','guía universitaria. Guía para el profesor y el alumno','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('171','Asesoramiento personal universitario','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('172','Electronica Integrata Digitale','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('173','Cane Sugar Engineering','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('174','Diseño de Sistemas Digitales y Microprocesadores','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('175','Image Acquisition and Processing with LabVIEW','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('176','Creating Human Machine Interfaces Using Visual Basic','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('177','Libro Blanco de la Automatización y Control en la industria de la caña de azúcar','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('178','A Hardward Interfacing and Control Protocol','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('179','Hands-On ZigBee','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('180','TCP/IP Sockets in C#: Practical Guide for Programmers','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('181','Intelligent Systems and Control','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('182','Análisis Estructural Avanzado','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('183','TECNIA: Revista técnico científica','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('184','IFAC Conference on System Structure and Control','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('185','10th World Congress on Automatic Control Volume 6','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('186','Estadística','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('187','Embedded Systems Architecture','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('188','Modern Methods of Image Processing and Pattern Recognition, Part 1','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('189','Modern Industrial Automation Software Design: Principles and Real-World Examples','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('190','System Invastigation of Programmable Systems on Chip (PSoC)','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('191','DSP - Electromechanical Motion Control','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('192','Closed-Loop Control with SIMATIC S5','2');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('193','Handbook of Networked and Embedded Control Systems','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('194','Fuzzy Logic, Identification and Predictive Control','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('195','FPGA Prototyping by VHDL examples','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('196','ARM System-on-chip architecture','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('197','Rapid Review of English Grammar','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('198','Hyperspectral Imaging Technology in Food and Agriculture','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('199','Diseño y aplicación de sistemas de medición ','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('200','Control Predictivo: Una técnica para el futuro de la industria','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('201','The Oxford Handbook of Innovation','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('202','AutoCAD Land Development Desktop: Getting Started Guide','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('203','Data Converters and Voltage References IC Handbook','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('204','Control automático de procesos','2');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('205','Industrial Moisture and humidity measurement','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('206','Handbook of dielectric and thermal properties of materials at microwave frecuencies','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('207','Modern SCADA protocols','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('208','A hands-on guide to effective embedded design','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('209','Count Riccati and the early days of the riccati equation','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('210','Autocad Land development Desktop: Users Guide','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('211','Learn digital design with PSOC a bit at a time','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('212','Oportunidades de inversión en el Perú','2');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('213','Cocoa and Coffe Fermentations','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('214','Internet of Things','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('215','Quinto Workshop Iberchip Memorias','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('216','Microalgae for Biofuel Production and CO2 Sequestration','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('217','Siam Review','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('218','Dendrocronología Básica','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('219','Pasión por la verdad: La responsabilidad del saber y la Universidad en el pensamiento de Juan Pablo II','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('220','Identification of Nonlinear Systems Using Neural Networks and Polynomial Models','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('221','Induction Motor Control Design','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('222','Embedded Design Using Programmable Gate Arrays','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('223','Guide to FPGA Implementation of Arithmetic Functions','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('224','Measurement Systems: Application and Design','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('225','Design for Embedded Image Processing on FPGAs','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('226','Mons. Josemaría Escrivá de Balaguer','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('227','Control Systems Theory','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('228','Scientific Computing with MATLAB and Octave','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('229','Solar Energy Engineering: Processes and Systems','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('230','Electrónica: serie apuntes','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('231','System-on-Chip: Next Generation Electronics','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('232','MATLAB para ingenieros ','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('233','Microsoft Visual C++: MFC Library Reference Part 2','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('234','Microsft Visual C++: Users Guides','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('235','Essays on Control: Perspective in the Theory and its Applications','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('236','Análisis Numérico y Visualización Gráfica con MATLAB','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('237','How Google Works','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('238','Ciencia, Tecnología, Innovación','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('239','Opinión pública 1921-2021','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('240','INTERCON 2001','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('241','No rules rules: Netflix and the Culture of Reinvention','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('242','Four: El ADN secreto de amazon, apple, facebook y google','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('243','La Tiepidezza','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('244','El asalto del cielo','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('245','Data and Model in Engineering, Science and Business','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('246','Nonlinear System Identification by Haar Wavelets','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('247','Security and Privacy in Internet of Things (IoTs)','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('248','Plan Bicentenario: El Perú hacia el 2021','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('249','Networked and Distributed Predictive Control','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('250','Block Oriented Identification of Nonlinear Systems','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('251','Adaptive Nonlinear System Identification','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('252','Teoria della Predizione e del Filtraggio','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('253','Adaptive Control of Solar Energy Collector Systems','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('254','Discrete Fourier Analysis and Wavelets','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('255','Nonlinear Model Predictive Control','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('256','New Trends in Control Theory','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('257','Nonlinear System Identification - Input-Output Modeling Approach Vol. 1','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('258','Nonlinear System Identification - Input-Output Modeling Approach Vol. 2','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('259','Juan Pablo II. Pregonero de la Verdad (Vol. II)','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('260','Lagire morale & le virtu','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('261','Filosofia della natura','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('262','Principles of combustion ','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('263','Python deep learning','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('264','Nonlinear identification using adaptive local linear neuro-fuzzy','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('265','La Serenidad: Una actitud ante el mundo','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('266','La actualidad del pensamiento cristiano','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('267','Juan Pablo II. Pregonero de la Verdad (Vol. I)','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('268','Cartas (I) Josémaría Escrivá de Balanguer: Obras Completas','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('269','La libertad en la familia','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('270','Jesús de Nazareth: desde la entrada en Jerusalén hasta la Resurrección','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('271','Preguiere','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('272','E Gesu che passa ','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('273','Políticas para impulsar la ciencia, la tecnología y la innovación tecnológica en el Perú','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('274','Dizionario dei sinonimi e dei contrari','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('275','Adaptive Control: selected solutions to accompany','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('276','Filosofia di dio','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('277','Nonlinear Process Control: Applications of Generic Model Control','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('278','Linear Systems and Optimal Control','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('279','Optimal Control with Engineering Applications','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('280','Nonlinear Systems (Vol. 1 Dynamics and Control)','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('281','Nonlinear Systems (Vol. 2 Applications to Bilinear Control)','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('282','System Identification Competition ','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('283','Wireless Sensor Networks','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('284','Linear Systems ','1');
INSERT INTO titulo(IdTitulo,titulo,cantidad)VALUES('285','Bioprocess Control','1');

-- si se van a agregar registros directamente a la DB hacerlo después de este comentario
