USE sac;

-- tabla miembros

INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('1','Elmer ','Calle Chojeda',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('2','José ','Oliden Semino',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('3','William','Ipanaqué Alama',1);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('4','Juan Carlos','Soto Bohórquez',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('5','Gerson','La Rosa',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('6','Ernesto','Paiva Peredo',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('7','Irene ','Alvarado Tabbachi',1);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('8','Jean','Campos',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('9','Bogdan','Dorneanu',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('10','Estefani','Almeyda',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('11','Carlos','Estrada',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('12','Ricard','Esparza Masana',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('13','Iván ','Belupú Amaya',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('14','Justo','Oquelis',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('15','Juan Junior','Valdiviezo Espinoza',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('16','José ','Castillo',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('17','Daniel ','Caravantes Samamé',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('18','Juan','Yeng',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('19','Kevin','Cotrina',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('20','Brain','Amaya',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('21','Eduardo','Correa',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('22','Melannie','García',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('23','Gustavo','Grosso',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('24','José','Huamantoma',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('25','Robert','Menzhausen',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('26','Nicole','Gehring',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('27','Andres Aramburu','Pardo Figueroa',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('28','José José','Manrique Silupú ',1);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('29','Harvey','Arellano Garcia ',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('30','Franco','Abanto',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('31','Pedro','Rotta',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('32','Luis','La Madrid',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('33','Gaby','Ruiz',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('34','Antonio','Criollo',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('35','Miguel','Mendoza',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('36','Eduardo','Saavedra',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('37','Gustavo','Vargas',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('38','Edson Rodrigo','Fernandez Cornejo',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('39','Ricardo','Cajo Diaz',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('40','Jayro','Paiva',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('41','Laura','Carrasco',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('42','Manuel','Merino',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('43','Eduardo','Pinos Vélez',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('44','Adrían','Cabrera',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('45','Andrea','Curay',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('46','Carlos Luis','Chacón',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('47','Luis','Serpa Andrade',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('48','Marlon','Chazi',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('49','Christian','Cajamarca',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('50','Vladimir','Robles Bykbaev',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('51','E.','Mejía Gamarra',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('52','F.','Reiter',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('53','P.','Tkachenko',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('54','Patrick','Schrangl',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('55','G.','Freckmann',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('56','Robin','De Keyser',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('57','K.','Checa',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('58','M.','Gamarra',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('59','Miguel','Delgado',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('60','Edson','Effio',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('61','Ney','Farfán',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('62','Jorge','Reyes',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('63','María','Flores Rivera',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('64','Deysi','Herrera Alvarez',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('65','Luigi','Del Re',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('66','David','Mendoza',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('67','Susana','Encalada',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('68','Edwin','Gamboa',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('69','Julio ','Salazar',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('70','Daniel ','Espinoza',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('71','César','Cherre',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('72','Oscar','Yañez',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('73','Gustavo','Silva',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('74','Martín A.','Capcha',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('75','Rocio','Alvarez Cardenas',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('76','Sebastian','Torres Ríos',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('77','Juan','Moreno Peña',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('78','Julio ','Salinas',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('79','Cesar','Chinguel',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('80','Jessica Magaly','Ruiz Reyes',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('81','Pablo','Parra Rosero',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('82','Guillermo','Granda',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('83','Flavio','Prieto',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('84','Jorge','Machacuay',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('85','Andres','Hernandez',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('86','Abhishek','Dutta',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('87','Armando','Rivadeneyra Bardales',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('88','Danilo','Soares Barboza',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('89','Martín','Flores',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('90','Marco','Lovera',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('91','Alberto','Leva',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('92','Riccardo','Scattolini',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('93','Rafael','Saavedra García Zabaleta',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('94','Jose','Dario Calderon',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('95','William','Solórzano Requejo',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('96','Lennin Fabrico','Morales Ticliahuanca',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('97','Julia','Acuña',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('98','Elías Saúd','Castillo Córdova',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('99','Jorge','Neira',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('100','Pool','Nolasco',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('101','Franco','Cunyarache',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('102','Michael','Sernaque',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('103','Reynaldo','Raygada Watanabe',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('104','Zulema Milenka','Ramírez Huancayo',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('105','María Daniela','Vega Jiménez',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('106','Rosa Luz','Benites de Beingolea',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('107','Alfonso Guillermo','Dulanto Rishing',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('108','Edilberto Horacio','Vásquez Diaz',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('109','Pedro Luis','Mendoza Guerrero',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('110','Javier Arturo','Bereche Álvarez',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('111','Miguel Enrique','Gallo Seminario',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('112','Dante','Guerrero Chanduví',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('113','Lenin','Nuñez Pintado',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('114','Erick','Arauco Moreno',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('115','Italo','Chinchay Ulloa',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('116','John','Gallo Ruiz',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('117','Valeria','Martinelli',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('118','Daniel','Marcelo',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('119','Jesús Andrés','Jara Puelles',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('120','Rodolfo','Rodríguez Arizmendiz',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('121','Rodrigo Idelso','Arreategui Palacios',3);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('122','Javier Alejandro','Machacuay Vera',1);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('123','Karlo Alonso','Cruz Herrera',3);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('124','Carlos Oswaldo','Cruz López',2);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('125','Jim Isai','Castillo Quezada',3);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('126','Juan Carlos','Sánchez Saucedo',3);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('127','Gonzalo','Morante',3);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('128','Carlos Aaron Justi','Lopez Velasquez',3);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('129','Eduardo Moisés','Crisanto Palacios',3);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('130','William Jesús','Valencia Macalupú',3);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('131','Jhon Leonardo','Oblitas Cruz',3);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('132','Cindy Pamela','Peláez Quispe',3);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('133','Manuel','Vargas',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('134','Diego ','Teixeira',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('135','Gabriela ','Jiménez',4);
INSERT INTO miembros(idMiembro,nombre,apellido,idCargo)VALUES('136','Max','Ladines',4);

-- si se van a agregar registros directamente a la DB hacerlo después de este comentario

